// homepage/src/lib/components/layout/Navigation.svelte
<script lang="ts">
	import type { NavItem } from '$lib/types';

	interface Props {
		items: NavItem[];
		mobile?: boolean;
		onnavigate?: () => void;
	}

	let { items, mobile = false, onnavigate }: Props = $props();

	function handleNavClick(event: MouseEvent, href: string) {
		if (href.startsWith('#')) {
			event.preventDefault();
			const target = document.querySelector(href);
			if (target) {
				target.scrollIntoView({ behavior: 'smooth' });
				window.history.pushState(null, '', href);
			}
		}
		// Notify parent that navigation occurred (for closing mobile menu)
		if (mobile && onnavigate) {
			onnavigate();
		}
	}

	function handleExternalClick() {
		// Also close mobile menu when clicking external links
		if (mobile && onnavigate) {
			onnavigate();
		}
	}
</script>

<nav class="navigation" class:mobile aria-label="Main navigation">
	<ul class="nav-list">
		{#each items as item}
			<li class="nav-item">
				{#if item.external}
					<a
						href={item.href}
						target="_blank"
						rel="noopener noreferrer"
						class="nav-link"
						aria-label="{item.label} (opens in new tab)"
						onclick={handleExternalClick}
					>
						{item.label}
					</a>
				{:else}
					<a
						href={item.href}
						class="nav-link"
						onclick={(e: MouseEvent) => handleNavClick(e, item.href)}
					>
						{item.label}
					</a>
				{/if}
			</li>
		{/each}
	</ul>
</nav>

<style>
	.navigation {
		display: flex;
		align-items: center;
	}

	.nav-list {
		display: flex;
		align-items: center;
		gap: var(--spacing-lg);
		list-style: none;
		margin: 0;
		padding: 0;
	}

	.nav-item {
		margin: 0;
	}

	.nav-link {
		display: inline-block;
		padding: var(--spacing-sm) var(--spacing-md);
		color: var(--color-text);
		font-weight: 500;
		text-decoration: none;
		border-radius: var(--border-radius-md);
		transition: color var(--transition-fast), background-color var(--transition-fast);
	}

	.nav-link:hover {
		color: var(--color-primary);
		background-color: var(--color-surface);
	}

	/* Mobile styles */
	.navigation.mobile {
		flex-direction: column;
		width: 100%;
	}

	.navigation.mobile .nav-list {
		flex-direction: column;
		width: 100%;
		gap: var(--spacing-sm);
	}

	.navigation.mobile .nav-item {
		width: 100%;
	}

	.navigation.mobile .nav-link {
		display: block;
		width: 100%;
		padding: var(--spacing-md);
		text-align: center;
		min-height: 44px;
		display: flex;
		align-items: center;
		justify-content: center;
	}

	@media (max-width: 768px) {
		.navigation:not(.mobile) {
			display: none;
		}
	}
</style>

// mirdb-homepage/src/components/Navigation/Navigation.tsx
/**
 * Navigation Component.
 * Owner: Scenario 6 - Navigation and External Links
 *
 * Provides navigation between page sections with:
 * - Links to Features, Usage, Roadmap sections
 * - Smooth scroll behavior
 * - Responsive design (hamburger menu on mobile)
 */

import { useState } from 'react'
import { GITHUB_REPO_URL } from '../../utils/constants'

interface NavLink {
  href: string
  label: string
  isExternal?: boolean
}

const navLinks: NavLink[] = [
  { href: '#features', label: 'Features' },
  { href: '#usage', label: 'Usage' },
  { href: '#roadmap', label: 'Roadmap' },
  { href: GITHUB_REPO_URL, label: 'GitHub', isExternal: true },
]

export function Navigation() {
  const [isMenuOpen, setIsMenuOpen] = useState(false)

  const handleNavClick = (e: React.MouseEvent<HTMLAnchorElement>, href: string) => {
    if (href.startsWith('#')) {
      e.preventDefault()
      const element = document.querySelector(href)
      if (element) {
        element.scrollIntoView({ behavior: 'smooth' })
      }
      setIsMenuOpen(false)
    }
  }

  return (
    <nav className="bg-white dark:bg-gray-900 shadow-sm sticky top-0 z-50">
      <div className="max-w-6xl mx-auto px-4">
        <div className="flex justify-between items-center h-16">
          {/* Logo */}
          <a
            href="/"
            className="text-xl font-bold text-gray-900 dark:text-white"
          >
            MirDB
          </a>

          {/* Desktop Navigation */}
          <div className="hidden md:flex items-center gap-6">
            {navLinks.map((link) => (
              <a
                key={link.href}
                href={link.href}
                onClick={(e) => handleNavClick(e, link.href)}
                {...(link.isExternal && {
                  target: '_blank',
                  rel: 'noopener noreferrer',
                })}
                className="text-gray-600 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 transition-colors"
              >
                {link.label}
              </a>
            ))}
          </div>

          {/* Mobile Menu Button */}
          <button
            type="button"
            onClick={() => setIsMenuOpen(!isMenuOpen)}
            className="md:hidden p-2 min-w-[44px] min-h-[44px] flex items-center justify-center text-gray-600 dark:text-gray-300 hover:text-gray-900 dark:hover:text-white"
            aria-expanded={isMenuOpen}
            aria-label={isMenuOpen ? 'Close menu' : 'Open menu'}
          >
            {isMenuOpen ? (
              <CloseIcon />
            ) : (
              <MenuIcon />
            )}
          </button>
        </div>

        {/* Mobile Navigation */}
        {isMenuOpen && (
          <div className="md:hidden py-4 border-t border-gray-200 dark:border-gray-700">
            <div className="flex flex-col gap-4">
              {navLinks.map((link) => (
                <a
                  key={link.href}
                  href={link.href}
                  onClick={(e) => handleNavClick(e, link.href)}
                  {...(link.isExternal && {
                    target: '_blank',
                    rel: 'noopener noreferrer',
                  })}
                  className="text-gray-600 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 transition-colors py-2 min-h-[44px] flex items-center"
                >
                  {link.label}
                </a>
              ))}
            </div>
          </div>
        )}
      </div>
    </nav>
  )
}

function MenuIcon() {
  return (
    <svg
      className="w-6 h-6"
      fill="none"
      stroke="currentColor"
      viewBox="0 0 24 24"
      aria-hidden="true"
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={2}
        d="M4 6h16M4 12h16M4 18h16"
      />
    </svg>
  )
}

function CloseIcon() {
  return (
    <svg
      className="w-6 h-6"
      fill="none"
      stroke="currentColor"
      viewBox="0 0 24 24"
      aria-hidden="true"
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={2}
        d="M6 18L18 6M6 6l12 12"
      />
    </svg>
  )
}

export default Navigation
