// homepage/src/components/Header.tsx
'use client';

import { useState, useCallback, useEffect } from 'react';
import { NAV_LINKS } from '@/lib/constants';
import { cn } from '@/lib/utils';

export default function Header() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  const toggleMobileMenu = useCallback(() => {
    setMobileMenuOpen((prev) => !prev);
  }, []);

  const closeMobileMenu = useCallback(() => {
    setMobileMenuOpen(false);
  }, []);

  // Close menu on Escape key
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && mobileMenuOpen) {
        setMobileMenuOpen(false);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [mobileMenuOpen]);

  // Prevent body scroll when mobile menu is open
  useEffect(() => {
    if (mobileMenuOpen) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
    return () => {
      document.body.style.overflow = '';
    };
  }, [mobileMenuOpen]);

  return (
    <header
      className={cn(
        'fixed top-0 left-0 right-0 z-50',
        'bg-[var(--background)]/80 backdrop-blur-md',
        'border-b border-[var(--border)]'
      )}
      data-testid="header"
    >
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16">
          {/* Logo / Brand */}
          <a
            href="#"
            className="text-xl font-bold text-[var(--foreground)] flex items-center gap-2"
            data-testid="header-logo"
          >
            <span className="text-brand-500">MirDB</span>
          </a>

          {/* Desktop Navigation - Horizontal links */}
          <nav
            className="hidden md:flex items-center gap-8"
            data-testid="desktop-nav"
            aria-label="Main navigation"
          >
            {NAV_LINKS.map((link) => (
              <a
                key={link.label}
                href={link.href}
                className={cn(
                  'text-sm font-medium text-[var(--muted-foreground)]',
                  'hover:text-[var(--foreground)] transition-colors'
                )}
              >
                {link.label}
              </a>
            ))}
          </nav>

          {/* Mobile hamburger - hidden on desktop */}
          <button
            type="button"
            className="md:hidden p-2 text-[var(--foreground)]"
            aria-label={mobileMenuOpen ? 'Close menu' : 'Open menu'}
            aria-expanded={mobileMenuOpen}
            aria-controls="mobile-nav-overlay"
            data-testid="mobile-menu-button"
            onClick={toggleMobileMenu}
          >
            {mobileMenuOpen ? (
              <svg
                className="w-6 h-6"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M6 18L18 6M6 6l12 12"
                />
              </svg>
            ) : (
              <svg
                className="w-6 h-6"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M4 6h16M4 12h16M4 18h16"
                />
              </svg>
            )}
          </button>
        </div>
      </div>

      {/* Mobile Navigation Overlay */}
      {mobileMenuOpen && (
        <div
          id="mobile-nav-overlay"
          className={cn(
            'md:hidden',
            'fixed top-16 left-0 right-0 z-40',
            'h-[calc(100vh-4rem)]',
            'bg-[var(--background)]/95 backdrop-blur-lg'
          )}
          data-testid="mobile-nav-overlay"
          role="dialog"
          aria-label="Mobile navigation menu"
          aria-modal="true"
        >
          <nav
            className="flex flex-col p-6 gap-2"
            aria-label="Mobile navigation"
            data-testid="mobile-nav"
          >
            {NAV_LINKS.map((link) => (
              <a
                key={link.label}
                href={link.href}
                className={cn(
                  'px-4 py-3 rounded-lg',
                  'text-lg font-medium text-[var(--foreground)]',
                  'hover:bg-[var(--card)] transition-colors'
                )}
                onClick={closeMobileMenu}
                data-testid="mobile-nav-link"
              >
                {link.label}
              </a>
            ))}
          </nav>
        </div>
      )}
    </header>
  );
}

// homepage/src/lib/components/layout/Header.svelte
<script lang="ts">
	import Navigation from './Navigation.svelte';
	import { NAV_ITEMS } from '$lib/utils/constants';

	let mobileMenuOpen = $state(false);

	function toggleMobileMenu() {
		mobileMenuOpen = !mobileMenuOpen;
	}

	function closeMobileMenu() {
		mobileMenuOpen = false;
	}
</script>

<header class="header">
	<div class="header-container container">
		<a href="/" class="logo" aria-label="MirDB Home">
			<span class="logo-text">MirDB</span>
		</a>

		<Navigation items={NAV_ITEMS} />

		<button
			class="mobile-menu-toggle"
			onclick={toggleMobileMenu}
			aria-expanded={mobileMenuOpen}
			aria-controls="mobile-menu"
			aria-label={mobileMenuOpen ? 'Close menu' : 'Open menu'}
		>
			<span class="hamburger-icon" class:open={mobileMenuOpen}>
				<span class="line"></span>
				<span class="line"></span>
				<span class="line"></span>
			</span>
		</button>
	</div>

	{#if mobileMenuOpen}
		<div
			id="mobile-menu"
			class="mobile-menu"
			role="dialog"
			aria-modal="true"
			aria-label="Mobile navigation"
		>
			<Navigation items={NAV_ITEMS} mobile={true} />
		</div>
		<button
			class="mobile-menu-overlay"
			onclick={closeMobileMenu}
			aria-label="Close menu"
		></button>
	{/if}
</header>

<style>
	.header {
		position: fixed;
		top: 0;
		left: 0;
		right: 0;
		z-index: 100;
		height: var(--header-height);
		background-color: var(--color-background);
		border-bottom: 1px solid var(--color-border);
		backdrop-filter: blur(8px);
	}

	.header-container {
		display: flex;
		align-items: center;
		justify-content: space-between;
		height: 100%;
	}

	.logo {
		display: flex;
		align-items: center;
		text-decoration: none;
		color: var(--color-text);
	}

	.logo-text {
		font-size: var(--font-size-xl);
		font-weight: 700;
		color: var(--color-primary);
	}

	.mobile-menu-toggle {
		display: none;
		padding: var(--spacing-sm);
		background: none;
		border: none;
		cursor: pointer;
	}

	.hamburger-icon {
		display: flex;
		flex-direction: column;
		justify-content: space-between;
		width: 24px;
		height: 18px;
	}

	.hamburger-icon .line {
		display: block;
		width: 100%;
		height: 2px;
		background-color: var(--color-text);
		border-radius: 1px;
		transition: transform var(--transition-fast), opacity var(--transition-fast);
	}

	.hamburger-icon.open .line:nth-child(1) {
		transform: translateY(8px) rotate(45deg);
	}

	.hamburger-icon.open .line:nth-child(2) {
		opacity: 0;
	}

	.hamburger-icon.open .line:nth-child(3) {
		transform: translateY(-8px) rotate(-45deg);
	}

	.mobile-menu {
		position: fixed;
		top: var(--header-height);
		left: 0;
		right: 0;
		background-color: var(--color-background);
		border-bottom: 1px solid var(--color-border);
		padding: var(--spacing-md);
		z-index: 99;
	}

	.mobile-menu-overlay {
		position: fixed;
		top: 0;
		left: 0;
		right: 0;
		bottom: 0;
		background-color: rgba(0, 0, 0, 0.5);
		z-index: 98;
		border: none;
		cursor: pointer;
	}

	@media (max-width: 768px) {
		.mobile-menu-toggle {
			display: block;
		}
	}
</style>
