// mirdb-homepage/src/components/ui/CodeBlock.tsx
/**
 * Code Block Component with Syntax Highlighting.
 * Owner: Scenario 3 - Usage Examples and Code Blocks
 *
 * Props:
 * - code: string
 * - language: string (e.g., 'rust', 'bash')
 * - filename?: string
 * - showCopyButton?: boolean
 *
 * Features:
 * - Prism.js syntax highlighting
 * - Copy to clipboard button
 * - Optional filename display
 */

import { useEffect, useRef } from 'react';
import Prism from 'prismjs';
import 'prismjs/components/prism-bash';
import { CopyButton } from './CopyButton';

export interface CodeBlockProps {
  code: string;
  language?: string;
  filename?: string;
  showCopyButton?: boolean;
  className?: string;
}

export function CodeBlock({
  code,
  language = 'bash',
  filename,
  showCopyButton = true,
  className = '',
}: CodeBlockProps) {
  const codeRef = useRef<HTMLElement>(null);

  useEffect(() => {
    if (codeRef.current) {
      Prism.highlightElement(codeRef.current);
    }
  }, [code, language]);

  return (
    <div className={`code-block relative rounded-lg overflow-hidden bg-gray-900 ${className}`}>
      {filename && (
        <div className="code-block-header flex items-center justify-between px-4 py-2 bg-gray-800 border-b border-gray-700">
          <span className="text-sm text-gray-400 font-mono">{filename}</span>
          {showCopyButton && (
            <CopyButton text={code} className="opacity-70 hover:opacity-100" />
          )}
        </div>
      )}
      <div className="relative">
        {!filename && showCopyButton && (
          <div className="absolute top-2 right-2 z-10">
            <CopyButton text={code} className="opacity-70 hover:opacity-100" />
          </div>
        )}
        <pre className="p-4 overflow-x-auto text-sm leading-relaxed">
          <code
            ref={codeRef}
            className={`language-${language}`}
            data-testid="code-content"
          >
            {code}
          </code>
        </pre>
      </div>
    </div>
  );
}

// homepage/src/lib/components/ui/CodeBlock.svelte
<!--
  Code Block Component
  Owner: Scenario 4 - Quick Start Section

  Props:
  - code: string
  - language: string
  - showCopy: boolean (default true)

  Displays syntax-highlighted code with copy button
-->
<script lang="ts">
	import CopyButton from './CopyButton.svelte';

	export let code: string;
	export let language: string = 'bash';
	export let showCopy: boolean = true;
</script>

<div class="code-block" data-testid="code-block" data-language={language}>
	<div class="code-header">
		<span class="code-language">{language}</span>
		{#if showCopy}
			<CopyButton text={code} />
		{/if}
	</div>
	<pre class="code-pre"><code class="code-content language-{language}">{code}</code></pre>
</div>

<style>
	.code-block {
		background-color: #1e1e1e;
		border-radius: var(--radius-lg);
		overflow: hidden;
		font-family: var(--font-family-mono);
		margin: var(--spacing-4) 0;
	}

	.code-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		padding: var(--spacing-3) var(--spacing-4);
		background-color: #2d2d2d;
		border-bottom: 1px solid #3d3d3d;
	}

	.code-language {
		font-size: var(--font-size-xs);
		color: #808080;
		text-transform: uppercase;
		letter-spacing: 0.05em;
	}

	.code-header :global(.copy-button) {
		background-color: transparent;
		border-color: #4d4d4d;
		color: #a0a0a0;
	}

	.code-header :global(.copy-button:hover) {
		background-color: #3d3d3d;
		color: #ffffff;
		border-color: #6d6d6d;
	}

	.code-header :global(.copy-button.copied) {
		color: var(--color-success);
		border-color: var(--color-success);
	}

	.code-pre {
		margin: 0;
		padding: var(--spacing-4);
		overflow-x: auto;
	}

	.code-content {
		color: #d4d4d4;
		font-size: var(--font-size-sm);
		line-height: 1.6;
		white-space: pre;
		display: block;
	}

	/* Basic syntax highlighting for bash */
	.code-content.language-bash {
		color: #9cdcfe;
	}
</style>
