// mirdb-homepage/src/components/Terminal/CopyButton.tsx
/**
 * Copy to Clipboard Button Component.
 * Owner: Scenario 3 - Interactive Terminal Component
 *
 * Expected features:
 * - Copy text to clipboard on click
 * - Visual feedback on successful copy
 * - Accessible button with aria-label
 * - Graceful degradation if Clipboard API unavailable
 */
import { useState, useEffect } from 'react';

interface CopyButtonProps {
  text: string;
  className?: string;
}

export function CopyButton({ text, className = '' }: CopyButtonProps) {
  const [copied, setCopied] = useState(false);
  const [isSupported, setIsSupported] = useState(true);

  useEffect(() => {
    // Check if Clipboard API is available
    setIsSupported(typeof navigator !== 'undefined' && !!navigator.clipboard);
  }, []);

  const handleCopy = async () => {
    if (!isSupported) return;

    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy text:', err);
    }
  };

  // Don't render button if clipboard API is not supported
  if (!isSupported) {
    return null;
  }

  return (
    <button
      type="button"
      onClick={handleCopy}
      className={`copy-button px-3 py-1.5 rounded text-sm font-mono transition-colors duration-200 ${
        copied
          ? 'bg-success text-background'
          : 'bg-surface text-text-secondary hover:bg-border hover:text-text-primary'
      } ${className}`}
      aria-label={copied ? 'Copied!' : 'Copy to clipboard'}
      data-testid="copy-button"
    >
      {copied ? (
        <span className="flex items-center gap-1" data-testid="copy-success">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className="h-4 w-4"
            viewBox="0 0 20 20"
            fill="currentColor"
            aria-hidden="true"
          >
            <path
              fillRule="evenodd"
              d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
              clipRule="evenodd"
            />
          </svg>
          Copied!
        </span>
      ) : (
        <span className="flex items-center gap-1">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className="h-4 w-4"
            viewBox="0 0 20 20"
            fill="currentColor"
            aria-hidden="true"
          >
            <path d="M8 3a1 1 0 011-1h2a1 1 0 110 2H9a1 1 0 01-1-1z" />
            <path d="M6 3a2 2 0 00-2 2v11a2 2 0 002 2h8a2 2 0 002-2V5a2 2 0 00-2-2 3 3 0 01-3 3H9a3 3 0 01-3-3z" />
          </svg>
          Copy
        </span>
      )}
    </button>
  );
}

// homepage/src/lib/components/ui/CopyButton.svelte
<!--
  Copy Button Component
  Owner: Scenario 4 - Quick Start Section

  Props:
  - text: string (content to copy)

  Events:
  - copied: CustomEvent (on successful copy)

  Shows visual feedback on copy success
-->
<script lang="ts">
	import { createEventDispatcher } from 'svelte';
	import { copyToClipboard } from '$lib/utils/clipboard';

	export let text: string;

	const dispatch = createEventDispatcher<{ copied: void }>();

	let copied = false;
	let copyTimeout: ReturnType<typeof setTimeout>;

	async function handleCopy() {
		const success = await copyToClipboard(text);
		if (success) {
			copied = true;
			dispatch('copied');

			// Reset copied state after 2 seconds
			clearTimeout(copyTimeout);
			copyTimeout = setTimeout(() => {
				copied = false;
			}, 2000);
		}
	}
</script>

<button
	type="button"
	class="copy-button"
	class:copied
	on:click={handleCopy}
	aria-label={copied ? 'Copied!' : 'Copy to clipboard'}
	data-testid="copy-button"
>
	{#if copied}
		<svg
			xmlns="http://www.w3.org/2000/svg"
			width="16"
			height="16"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			stroke-width="2"
			stroke-linecap="round"
			stroke-linejoin="round"
			aria-hidden="true"
		>
			<polyline points="20 6 9 17 4 12"></polyline>
		</svg>
		<span class="copy-text">Copied!</span>
	{:else}
		<svg
			xmlns="http://www.w3.org/2000/svg"
			width="16"
			height="16"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			stroke-width="2"
			stroke-linecap="round"
			stroke-linejoin="round"
			aria-hidden="true"
		>
			<rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
			<path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
		</svg>
		<span class="copy-text">Copy</span>
	{/if}
</button>

<style>
	.copy-button {
		display: inline-flex;
		align-items: center;
		gap: var(--spacing-2);
		padding: var(--spacing-2) var(--spacing-3);
		background-color: transparent;
		border: 1px solid var(--color-border);
		border-radius: var(--radius-md);
		color: var(--color-text-muted);
		font-size: var(--font-size-sm);
		font-family: var(--font-family);
		cursor: pointer;
		transition: all var(--transition-fast);
	}

	.copy-button:hover {
		background-color: var(--color-surface);
		color: var(--color-text);
		border-color: var(--color-text-muted);
	}

	.copy-button:focus-visible {
		outline: 2px solid var(--color-primary);
		outline-offset: 2px;
	}

	.copy-button.copied {
		color: var(--color-success);
		border-color: var(--color-success);
	}

	.copy-text {
		display: none;
	}

	@media (min-width: 768px) {
		.copy-text {
			display: inline;
		}
	}
</style>
